### ISSUE TITLE
My mc keeps crashing ill include my crash log and mods here : (Btw my discord name is MercilessRage#2778) msg me if you know a way to resolve dis

### ISSUE THREAD

**Issue by SkyBlockSweat** [NotEnoughCoins/NotEnoughCoins#46]
![image](https://user-images.githubusercontent.com/97385532/148678361-95f7d1f7-946d-4340-b757-c65af8af9cb7.png)
Btw im not using forge but skyclient bc its more smoother
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  NotEnoughCoins FTW (NotEnoughCoins-0.9.2-all.jar)
  ModTweaker (Patcher-1.7.0 (1.8.9).jar)
  PatcherTweaker (Patcher-1.7.0 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/1/22 3:57 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at me.mindlessly.notenoughcoins.utils.updater.GitHub.getLatestVersion(GitHub.java:46)
	at me.mindlessly.notenoughcoins.utils.updater.GitHub.isLatest(GitHub.java:42)
	at me.mindlessly.notenoughcoins.events.OnGuiOpen.onGuiOpen(OnGuiOpen.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_OnGuiOpen_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:908)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:505)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:91)
	at gg.essential.loader.stage2.EssentialLoader.addToClasspath(EssentialLoader.java:86)
	at gg.essential.loader.stage2.EssentialLoaderBase.addToClasspath(EssentialLoaderBase.java:320)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.mindlessly.notenoughcoins.utils.updater.GitHub.getLatestVersion(GitHub.java:46)
	at me.mindlessly.notenoughcoins.utils.updater.GitHub.isLatest(GitHub.java:42)
	at me.mindlessly.notenoughcoins.events.OnGuiOpen.onGuiOpen(OnGuiOpen.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_OnGuiOpen_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:908)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:91)
	at gg.essential.loader.stage2.EssentialLoader.addToClasspath(EssentialLoader.java:86)
	at gg.essential.loader.stage2.EssentialLoaderBase.addToClasspath(EssentialLoaderBase.java:320)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 660948608 bytes (630 MB) / 1409286144 bytes (1344 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version      | Source                                        |
	| ------ | ----------------------- | ------------ | --------------------------------------------- |
	| UCHIJA | mcp                     | 9.19         | minecraft.jar                                 |
	| UCHIJA | FML                     | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar            |
	| UCHIJA | Forge                   | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar            |
	| UCHIJA | essential               | 1.0.0        | Essential (forge_1.8.9).jar                   |
	| UCHIJA | sbp                     | 1.5.4.2      | 1.8.9 SkyblockPersonalized 1.5.4.2.jar        |
	| UCHIJA | Danker's Skyblock Mod   | 1.8.7-beta4  | 1.8.9.Danker.s.Skyblock.Mod.-.1.8.7-beta4.jar |
	| UCHIJA | skyblock_dungeons_guide | 1.0          | dungeonsguide-3.6.0.jar                       |
	| UCHIJA | itlt                    | 1.0.1        | itlt-1.8.8-9-1.0.1.jar                        |
	| UCHIJA | nec                     | v0.9.2       | NotEnoughCoins-0.9.2-all.jar                  |
	| UCHIJA | notenoughupdates        | 2.0.0-REL    | NotEnoughUpdates-2.0.0.jar                    |
	| UCHIJA | patcher                 | 1.7.0        | Patcher-1.7.0 (1.8.9).jar                     |
	| UCHIJA | text_overflow_scroll    | 1.4.0        | Scrollable Tooltips-1.4 (1.8.9).jar           |
	| UCHIJA | skyblockaddons          | 1.6.1        | SkyblockAddons-1.6.1-for-MC-1.8.9.jar         |
	| UCHIJA | skyblockhud             | 1.13         | SkyblockHud-1.13-beta7.jar                    |

	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
NotEnoughCoins FTW (NotEnoughCoins-0.9.2-all.jar)
  me.mindlessly.notenoughcoins.tweaker.NotEnoughCoinsTransformer
ModTweaker (Patcher-1.7.0 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
PatcherTweaker (Patcher-1.7.0 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Worlds and Beyond [16x] - Release 1.5.zip, RNBW+ v0.7.0.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics

**Comment by RobotHanzo** [comment]
Download the latest version

**Comment by SkyBlockSweat** [comment]
Download what?????

**Comment by RobotHanzo** [comment]
https://github.com/NotEnoughCoins/NotEnoughCoins/releases/tag/v0.9.2.1

**Comment by SkyBlockSweat** [comment]
It works!
