### ISSUE TITLE
Error on loading version 1.0

### ISSUE THREAD

**Issue by rysiuwroc** [NotEnoughCoins/NotEnoughCoins#58]
first error in log:
`[21:53:36] [main/ERROR]: Coremod NotEnoughCoinsLoadingPlugin: Unable to class load the plugin me.mindlessly.notenoughcoins.tweaker.NotEnoughCoinsLoadingPlugin
java.lang.ClassNotFoundException: me.mindlessly.notenoughcoins.tweaker.NotEnoughCoinsLoadingPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:536) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:241) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:168) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:154) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:142) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134) [Essential%20(forge_1.8.9).jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:18) [Essential%20(forge_1.8.9).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at gg.essential.loader.stage1.EssentialSetupTweaker$Forge$Impl.setupSourceFile(EssentialSetupTweaker.java:173) [stage1.jar:5]
	at gg.essential.loader.stage1.EssentialSetupTweaker$Forge$Impl.setupPostLoad(EssentialSetupTweaker.java:122) [stage1.jar:5]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:46) [stage1.jar:5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) [NotEnoughCoins-1.0-all.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) [NotEnoughCoins-1.0-all.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:121) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:67) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191) [stage2.forge_1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110) [stage1.jar:5]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44) [stage1.jar:5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) [NotEnoughCoins-1.0-all.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) [NotEnoughCoins-1.0-all.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`
second error in log:
`[21:54:10] [Client thread/ERROR]: NotEnoughCoins have been disabled due to an error while authenticating. Please check the logs for more information.`

Same thing happens when NEC is the only mod trying to run. 
Forge reinstalled multiple times.
.minecraft folder deletion for fresh minecraft setup didn't help.

**Comment by Futuremappermydud** [comment]
Im having the same issue
