### ISSUE TITLE
Mod no longer displays flips (ValidatorException)

### ISSUE THREAD

**Issue by SmartGecko44** [NotEnoughCoins/NotEnoughCoins#71]
Every time I enable the flipper it just throws a ValidatorException. I use the premium version.

Stacktrace:
```
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.utils.Utils.getJson(Utils.java:53)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.utils.ApiHandler.getItems(ApiHandler.java:251)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client.flip(Client.java:27)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client.lambda$start$0(Client.java:19)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client$$Lambda$734/1748112284.run(Unknown Source)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:53:02] [pool-42-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.lang.Thread.run(Thread.java:745)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 29 more
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[18:53:02] [pool-42-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 35 more
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.utils.Utils.getJson(Utils.java:53)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.utils.ApiHandler.getItems(ApiHandler.java:251)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client.flip(Client.java:27)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client.lambda$start$0(Client.java:19)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at me.mindlessly.notenoughcoins.client.Client$$Lambda$734/1748112284.run(Unknown Source)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:53:04] [pool-43-thread-1/INFO]: [me.mindlessly.notenoughcoins.utils.Utils:getJson:57]: 	at java.lang.Thread.run(Thread.java:745)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 29 more
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[18:53:04] [pool-43-thread-1/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 35 more
```

**Comment by mindlesslydev** [comment]
Fixed in latest
